Document: spikesorter
Title: Debian spikesorter Manual
Author: <insert document author here>
Abstract: This manual describes what spikesorter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spikesorter/spikesorter.sgml.gz

Format: postscript
Files: /usr/share/doc/spikesorter/spikesorter.ps.gz

Format: text
Files: /usr/share/doc/spikesorter/spikesorter.text.gz

Format: HTML
Index: /usr/share/doc/spikesorter/html/index.html
Files: /usr/share/doc/spikesorter/html/*.html
